# Generated by Django 4.2 on 2023-06-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_banner_video_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner_video',
            options={'ordering': ['name'], 'verbose_name_plural': 'Banner_video'},
        ),
        migrations.AlterField(
            model_name='banner_video',
            name='video',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
