# Generated by Django 4.1.7 on 2023-07-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_banner_video_options_alter_banner_video_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tims',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('games', models.IntegerField()),
                ('win', models.IntegerField()),
                ('draw', models.IntegerField()),
                ('lose', models.IntegerField()),
                ('t_f', models.IntegerField()),
                ('o', models.IntegerField()),
                ('img', models.ImageField(upload_to='Jadval/')),
            ],
        ),
    ]
